/* Figure 2B v4.1 — local-section audit. Classic scripts support file://. */
(() => {
'use strict';
const data=window.FIGURE_DATA,$=id=>document.getElementById(id),byId=new Map(data.elements.map(e=>[e.id,e])),groups=new Map(data.groups.map(g=>[g.id,g]));
const pathKinds=['生成','利用','維持','訂正','継承','社会的伝達'];
const state={layers:Object.fromEntries(data.groups.map(g=>[g.id,g.default])),regions:Object.fromEntries(data.elements.filter(e=>e.type==='region'&&e.space!=='panel').map(e=>[e.id,e.visibleByDefault])),paths:Object.fromEntries(pathKinds.map(k=>[k,true])),selected:null,labelMode:'compact',preset:'overview',focus:true,compare:false,compareA:'ex-bacteria',compareB:'ex-thermostat',sigmaByExample:Object.fromEntries(data.elements.filter(e=>e.type==='example').map(e=>[e.id,e.defaultSigma||'local']))};
const palette={'生成':0x568d82,'利用':0x377a9b,'維持':0x8e6aa5,'訂正':0xb28a45,'継承':0x7975ab,'社会的伝達':0x9b6c86};
let scene,camera,renderer,raycaster,viewReady=false,scheduled=false,target;
let spherical={theta:.83,phi:1.06,radius:40};
const objects=new Map(),labelEntries=[],pickables=[];let associationGroup,selectionHalo;
let focusIds=new Set(),primaryIds=new Set(),directLinks=[];
const initialDetail=$('detail-content').innerHTML;
const kindNames={node:'関係概念',region:'候補領域',example:'事例 / 関係束',path:'因果経路'};
function dom(tag,cls,text){const x=document.createElement(tag);if(cls)x.className=cls;if(text!==undefined)x.textContent=text;return x;}
function btn(text,fn,cls=''){const b=dom('button',cls,text);b.onclick=fn;return b;}
function section(p,title,text){if(!text)return;const s=dom('section','audit-section');s.append(dom('h3','',title),dom('p','',text));p.append(s);return s;}
function listSection(p,title,items,cls=''){const s=dom('section','audit-section');s.append(dom('h3','',title));if(items?.length){const ul=dom('ul',cls);items.forEach(t=>ul.append(dom('li','',t)));s.append(ul);}else s.append(dom('p','muted','未指定'));p.append(s);return s;}
function check(container,label,color,checked,change,id){const l=dom('label','check-row'),c=document.createElement('input');c.type='checkbox';c.checked=checked;c.id=id;c.onchange=()=>change(c.checked);l.append(c);if(color){const dot=dom('span','dot');dot.style.background=color;l.append(dot);}l.append(document.createTextNode(label));container.append(l);return c;}
function baseActive(e){if(!state.layers[e.group])return false;if(e.type==='region'&&e.space!=='panel'&&!state.regions[e.id])return false;return e.type!=='path'||state.paths[e.kind];}
function active(e){return baseActive(e)||(state.focus&&focusIds.has(e.id));}
function modeFor(e){return e?.type==='example'?e.sigmaModes?.[state.sigmaByExample[e.id]]:null;}
function associationIds(e){const m=modeFor(e);return e.type==='example'?(m?.relations||[]):(e.relations||[]).map(r=>r.target);}
function seedInfo(id){const e=byId.get(id);if(!e)return;const m=modeFor(e);const paths=m?m.causalPaths:e.causalPaths||[];const analytic=m?m.analytics:e.analytics||[];const ids=associationIds(e);focusIds.add(id);primaryIds.add(id);
 for(const r of ids){if(!byId.has(r))continue;focusIds.add(r);directLinks.push([id,r]);}
 // Explicit region-membership records; geometry is never consulted.
 if(e.type==='example')for(const r of data.elements.filter(x=>x.type==='region'&&x.members))if(r.members.some(x=>ids.includes(x))){focusIds.add(r.id);directLinks.push([id,r.id]);}
 if(e.type!=='example'&&e.type!=='path')for(const c of data.elements.filter(x=>x.type==='example'))if(associationIds(c).includes(id)){focusIds.add(c.id);directLinks.push([id,c.id]);}
 for(const r of analytic||[])focusIds.add(r);
 for(const p of paths||[]){const pe=byId.get(p);if(!pe)continue;focusIds.add(p);focusIds.add(pe.source);focusIds.add(pe.target);}
 if(e.type==='path'){focusIds.add(e.source);focusIds.add(e.target);}
 if(e.group==='process')for(const p of data.elements.filter(x=>x.type==='path'&&(x.source===id||x.target===id))){focusIds.add(p.id);focusIds.add(p.source);focusIds.add(p.target);}
}
function computeFocus(){focusIds=new Set();primaryIds=new Set();directLinks=[];if(state.compare){seedInfo(state.compareA);seedInfo(state.compareB);}else if(state.selected)seedInfo(state.selected);if(boundary.enabled){for(const r of boundaryRecords())focusIds.add(r.anchor);for(const r of usageNow()?.relations||[])focusIds.add(anchor(r));}}
function showMobile(panel){if(innerWidth>760)return;const opening=!$(panel).classList.contains('open');$('layers').classList.remove('open');$('detail').classList.remove('open');if(opening)$(panel).classList.add('open');updateMobileButtons();}
function updateMobileButtons(){$('toggle-layers').setAttribute('aria-expanded',String($('layers').classList.contains('open')));$('toggle-detail').setAttribute('aria-expanded',String($('detail').classList.contains('open')));}
function openAudit(){if(innerWidth<=760){$('layers').classList.remove('open');$('detail').classList.add('open');updateMobileButtons();}}
function sync(){computeFocus();for(const [id,obj]of objects)obj.visible=active(byId.get(id));for(const g of data.groups){const c=$('layer-'+g.id);c.checked=state.layers[g.id];c.indeterminate=!c.checked&&state.focus&&data.elements.some(e=>e.group===g.id&&focusIds.has(e.id));}
 for(const id in state.regions){const c=$('region-'+id);c.checked=state.regions[id];c.indeterminate=!c.checked&&state.focus&&focusIds.has(id);}for(const k of pathKinds)$('path-'+k).checked=state.paths[k];$('focus-mode').checked=state.focus;$('compare-toggle').setAttribute('aria-pressed',String(state.compare));$('compare-toggle').classList.toggle('compare-active',state.compare);
 document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.preset));$('view-description').textContent=data.viewDescriptions[state.preset]||'手動で選んだレイヤーの局所断面。接続は登録データに基づき、位置から推定しません。';
 const count=focusIds.size;$('focus-summary').textContent=count?(state.focus?`${count} 関連対象を強調／その他は背景表示`:'Focus OFF：全体濃度で表示'):'対象を選ぶと、関連要素を強調します。';
 renderAnalytics();renderList();renderAssociations();applyFocusStyle();renderBoundary();schedule();}
function renderList(){const q=$('search').value.trim().toLowerCase();$('object-list').replaceChildren();for(const e of data.elements){if(e.type==='path'||(!active(e)&&!q))continue;if(q&&!`${e.label} ${e.id} ${e.description}`.toLowerCase().includes(q))continue;const b=btn(e.label,()=>select(e.id));b.setAttribute('aria-pressed',String(primaryIds.has(e.id)));if(state.focus&&focusIds.size&&!focusIds.has(e.id))b.style.opacity='.48';$('object-list').append(b);}}
function contextTable(p,ctx){const labels={sigma:'Σ 対象系',contrasts:'𝒟 対照集合',mechanism:'M 機構',q:'Q 帰結',tauResponse:'τresponse',tauUpdate:'τupdate'};const t=dom('table','context-table');for(const [k,label]of Object.entries(labels)){const tr=dom('tr');tr.append(dom('th','',label),dom('td','',ctx?.[k]||'未指定'));t.append(tr);}p.append(t);}
function tagSection(p,title,tags,labels,basis,cls){const s=dom('section','audit-section');s.append(dom('h3','',title));if(!tags?.length)s.append(dom('p','muted','未指定'));else{for(const t of tags){const el=dom('span',cls,labels[t]||t);el.title=basis?.[t]||'作業的な参加候補。強度を示さない。';s.append(el);}const details=dom('details');details.append(dom('summary','tag-help','タグの根拠・適用範囲'));for(const t of tags)details.append(dom('p','tag-help',`${labels[t]||t}：${basis?.[t]||'この境界で検査する型。具体的成立は未確定。'}`));s.append(details);}p.append(s);}
function referenceList(p,refs){if(!refs?.length)return;const box=dom('div','references');for(const r of refs){if(!/^https?:\/\//.test(r.url))continue;const a=dom('a','',r.label);a.href=r.url;a.target='_blank';a.rel='noopener noreferrer';box.append(a,document.createElement('br'));}p.append(box);}
function evidenceBadge(record){return dom('span','evidence-badge '+(record?.status||''),record?data.evidenceLabels[record.status]||'? 未確定':'— 未設定');}
function evidenceDetail(p,caseLabel,rid,record){p.replaceChildren();p.append(dom('h4','',`${caseLabel} / ${byId.get(rid)?.label||rid}`),evidenceBadge(record),dom('p','',record?.basis||'このΣについての評価を登録していません。'));referenceList(p,record?.references);}
function sigmaSelector(e,onchange,id){const l=dom('label','select-label sigma-select','Σ Boundary Mode');const s=dom('select');s.id=id;for(const [key,label]of Object.entries(e.sigmaModes||{}).map(([k,v])=>[k,v.label||v.auditContext?.sigma||k])){const o=dom('option','',label+(e.sigmaModes?.[key]?'':'（未設定）'));o.value=key;o.disabled=!e.sigmaModes?.[key];s.append(o);}s.value=state.sigmaByExample[e.id];s.onchange=()=>onchange(s.value);l.append(s);return l;}
function setSigma(id,key){const e=byId.get(id);if(!e?.sigmaModes?.[key])return;state.sigmaByExample[id]=key;boundary.scopeView='current';sync();renderDetail();}
function analyticNotes(p,ids){if(!ids?.length)return;const s=dom('section','audit-section');s.append(dom('h3','','横断解析との接続'));for(const id of ids){const e=byId.get(id);if(!e)continue;const box=dom('div','analysis-note');box.append(dom('strong','',id==='analysis-Shannon'?'Shannonで分析可能〔条件付き〕':'Kolchinsky & Wolpert〔照合候補〕'),dom('p','',id==='analysis-Shannon'?'変数・分布・同時分布・対照集合・粒度・必要ならチャネルの指定が必要。解析結果は未計算。':'viabilityへの因果的寄与を評価する横断解析。M3全般の内容理論と同一視しない。'));box.append(btn('解析の条件を見る',()=>select(id),'text-button'));s.append(box);}p.append(s);}
function caseDetails(p,e,m){p.append(sigmaSelector(e,k=>setSigma(e.id,k),'sigma-select'));p.append(dom('p','scope-note','対象系が変わったため、別の命題を評価しています。選んだΣごとに関係・根拠・経路を切り替えます。'));section(p,'現在の対象命題',m?.description||'未指定');const note=dom('div','callout');note.append(dom('p','',`Fo：${m?.foAssessment||'未指定'}`),dom('p','',`UI候補：${m?.uiAssessment||'未指定'}`));p.append(note);listSection(p,'身体外・外部装置との接続',m?.externalConnections);
 const s=dom('section','audit-section');s.append(dom('h3','','関係束と帰属根拠の状態'),dom('p','tag-help','評価はこの事例・このΣについてのもの。概念の強弱や生命らしさの順位ではありません。'));const details=dom('div','pinned-evidence');details.append(dom('p','muted','状態ラベルを押すと、判断理由を表示します。'));const keys=[...new Set([...(m?.relations||[]),...Object.keys(m?.evidence||{})])];for(const rid of keys){const r=byId.get(rid)||byId.get(anchor(rid));const row=dom('div','evidence-row');row.append(btn(rid,()=>r&&select(r.id)));const b=btn('',()=>evidenceDetail(details,e.label,rid,m?.evidence?.[rid]));b.append(evidenceBadge(m?.evidence?.[rid]));row.append(b);s.append(row);}s.append(details);p.append(s);}
function renderDetail(){if(state.compare){renderComparison();return;}const e=byId.get(state.selected);if(!e){$('detail-content').innerHTML=initialDetail;return;}const m=modeFor(e),p=$('detail-content');p.replaceChildren();const close=btn('閉じる',()=>{$('detail').classList.remove('open');updateMobileButtons();},'detail-close');p.append(close);p.append(dom('p','kind',e.space==='panel'?'横断解析 / 座標外':e.group==='process'?'因果機構・状態':kindNames[e.type]));p.append(dom('h2','',e.label));if(e.type==='example')caseDetails(p,e,m);
 section(p,'A｜作業定義',e.description);listSection(p,'B｜成立根拠：何を観測・介入するか',e.auditQuestions);section(p,'C｜混同しやすいもの',e.confusions);listSection(p,'D｜禁止される飛躍',e.forbiddenInferences,'forbidden-list');section(p,'E｜代表事例',e.examples);p.append(dom('h3','','F｜Σ・𝒟・M・Q・τ'));contextTable(p,m?.auditContext||e.auditContext);
 tagSection(p,'拘束タイプの束',m?m.constraintTypes:e.constraintTypes,data.constraintLabels,m?.constraintBasis||e.constraintBasis,'constraint-tag');p.append(dom('p','tag-help','参加する拘束型の候補。強度・確率・測定値ではありません。'));
 tagSection(p,'形成履歴候補',m?m.formationHistory:e.formationHistory,data.historyLabels,m?.formationBasis||e.formationBasis,'history-tag');p.append(dom('p','tag-help','形成履歴と現在の変更しやすさは別属性です。'));
 analyticNotes(p,m?m.analytics:e.analytics);const links=associationIds(e);if(links.length&&e.type!=='example'){p.append(dom('h3','','参照・監査上の接続候補（含意なし）'));const tags=dom('div','tags');for(const id of links){const r=byId.get(id);if(r)tags.append(btn(r.shortLabel||r.label,()=>select(id)));}p.append(tags);}
 section(p,'備考',e.notes);referenceList(p,e.references);if(e.position)p.append(btn('局所断面を画面に収める',fitFocus,'focus-button'));if(data.twoDConditionsUrl){const a=dom('a','placeholder-link','2D成立条件図で確認');a.href=data.twoDConditionsUrl;p.append(a);}else{const b=btn('2D成立条件図で確認（リンク未設定）',()=>{},'placeholder-link');b.disabled=true;p.append(b);}p.append(dom('p','layer-note','Focus中の関連要素は、OFFレイヤーでも一時表示します。チェックの横棒が目印です。Focusを解除すると手動設定に戻ります。'));
}
function select(id){if(!byId.has(id))return;state.selected=id;state.compare=false;if(byId.get(id).type==='example'){boundary.caseId=id;if(id==='ex-bacteria')boundary.enabled=true;}sync();renderDetail();openAudit();}
function comparisonSelect(id,selected,onchange){const s=dom('select');s.id=id;for(const e of data.elements.filter(e=>e.type==='example')){const o=dom('option','',e.label);o.value=e.id;s.append(o);}s.value=selected;s.onchange=()=>onchange(s.value);return s;}
function setCompare(a,b){if(a)state.compareA=a;if(b)state.compareB=b;state.compare=true;state.selected=null;sync();renderDetail();openAudit();}
function renderComparison(){const p=$('detail-content');p.replaceChildren();p.append(btn('閉じる',()=>{$('detail').classList.remove('open');updateMobileButtons();},'detail-close'),dom('p','kind','COMPARE / 同じ関係・異なる対象命題'),dom('h2','','2事例の局所断面を比較'));
 const presets=dom('div','compare-presets');for(const [label,a,b]of data.comparisonPresets)presets.append(btn(label,()=>setCompare(a,b)));p.append(presets);const inputs=dom('div','compare-inputs');for(const [slot,id]of [['A',state.compareA],['B',state.compareB]]){const e=byId.get(id),box=dom('div');box.append(dom('label','',`事例${slot}`),comparisonSelect('compare-'+slot,id,v=>setCompare(slot==='A'?v:null,slot==='B'?v:null)),sigmaSelector(e,k=>setSigma(e.id,k),'compare-sigma-'+slot));inputs.append(box);}p.append(inputs);p.append(dom('p','scope-note','Σを変えると、別の対象命題を評価します。FoとUIは独立判定。合計点・ランキングは作りません。'));p.append(dom('p','tag-help','未設定は未評価。弱い・未確定とは区別します。「強い根拠」には構成を条件とする根拠も含み、実験済みとは限りません。'));
 const a=byId.get(state.compareA),b=byId.get(state.compareB),am=modeFor(a),bm=modeFor(b);const tab=dom('table','compare-table'),head=dom('tr');head.append(dom('th','','関係'),dom('th','','事例A'),dom('th','','事例B'));tab.append(head);const details=dom('div','evidence-detail');details.append(dom('p','muted','各評価を押すと、そのΣでの判断理由を表示します。'));
 const keys=[...new Set([...data.comparisonRelations,...Object.keys(am?.evidence||{}),...Object.keys(bm?.evidence||{})])];for(const rid of keys){const tr=dom('tr'),r=byId.get(rid),th=dom('th');th.textContent=rid==='reg-ui'?'UI候補':r?.shortLabel||rid;tr.append(th);for(const [e,m]of [[a,am],[b,bm]]){const td=dom('td'),rec=m?.evidence?.[rid];const bt=btn('',()=>evidenceDetail(details,e.label,rid,rec));bt.append(evidenceBadge(rec));td.append(bt);tr.append(td);}tab.append(tr);}p.append(tab,details);
 for(const [name,e,m]of [['A',a,am],['B',b,bm]]){section(p,`事例${name}｜${e.label}`,m?.description||'未指定');section(p,'Fo / UIを別に評価',`Fo：${m?.foAssessment||'未指定'} UI：${m?.uiAssessment||'未指定'}`);contextTable(p,m?.auditContext);tagSection(p,'拘束タイプ',m?.constraintTypes,data.constraintLabels,m?.constraintBasis,'constraint-tag');tagSection(p,'形成履歴候補',m?.formationHistory,data.historyLabels,m?.formationBasis,'history-tag');}
 p.append(btn('比較する局所断面を画面に収める',fitFocus,'focus-button'));p.append(btn('比較を終了',()=>{state.compare=false;state.selected=null;sync();renderDetail();},'focus-button'));}
function clearFocus(){state.selected=null;state.compare=false;sync();renderDetail();}
function renderAnalytics(){$('analysis-panels').replaceChildren();for(const e of data.elements.filter(e=>e.space==='panel'&&active(e))){const card=dom('div','analysis-card'+(state.focus&&focusIds.size&&!focusIds.has(e.id)?' dim':''));card.append(dom('h3','',e.label),dom('p','',e.description),btn('解析条件',()=>select(e.id)));$('analysis-panels').append(card);}}
function makeLabel(e,pos){const b=dom(e?'button':'span','scene-label'+(e?' '+e.type:''),e?.shortLabel||e?.label||'');if(e){b.title=e.label;b.setAttribute('aria-label',e.label);b.onclick=ev=>{ev.stopPropagation();select(e.id);};}else b.classList.add('axis');$('labels').append(b);labelEntries.push({el:b,e,pos});return b;}
function vec(a){return new THREE.Vector3(...a);}
function disposeGroup(g){while(g.children.length){const c=g.children[0];g.remove(c);c.traverse(o=>{o.geometry?.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material?.dispose();});}}
function curveBetween(a,b,bend=.5){const mid=a.clone().add(b).multiplyScalar(.5);mid.y+=bend;return new THREE.QuadraticBezierCurve3(a,mid,b);}
function lineCurve(curve,color,dashed=false,opacity=.75){const geom=new THREE.BufferGeometry().setFromPoints(curve.getPoints(32));const opts={color,transparent:true,opacity,depthWrite:false};const mat=dashed?new THREE.LineDashedMaterial({...opts,dashSize:.23,gapSize:.17}):new THREE.LineBasicMaterial(opts);const line=new THREE.Line(geom,mat);if(dashed)line.computeLineDistances();return line;}
function renderAssociations(){if(!viewReady)return;disposeGroup(associationGroup);selectionHalo.visible=false;if(!state.focus)return;const seen=new Set();for(const [a,b]of directLinks){const key=[a,b].sort().join('|');if(seen.has(key))continue;seen.add(key);const ae=byId.get(a),be=byId.get(b);if(!ae?.position||!be?.position||ae.type==='region'||be.type==='region'||!active(ae)||!active(be))continue;associationGroup.add(lineCurve(curveBetween(vec(ae.position),vec(be.position),.15),0x668991,true,.48));}const e=byId.get(state.selected);if(e?.position&&e.type!=='region'&&e.type!=='path'){selectionHalo.position.set(...e.position);selectionHalo.visible=true;}}
function applyFocusStyle(){if(!viewReady)return;const focused=state.focus&&focusIds.size>0;for(const [id,obj]of objects){const e=byId.get(id),related=focused&&focusIds.has(id),selected=primaryIds.has(id);if(e.type==='region'){obj.material.opacity=focused?(related?(id==='reg-bundle'?.09:.16):.012):(id==='reg-bundle'?.035:.055);for(const ch of obj.children)if(ch.material)ch.material.opacity=focused?(related?.22:.025):.07;continue;}
 if(e.type==='path'){const opacity=focused?(related?.90:.055):.25;obj.traverse(o=>{if(o.material){o.material.transparent=true;o.material.opacity=opacity;o.material.depthWrite=false;}});continue;}
 obj.scale.setScalar(selected?1.5:related?1.13:1);obj.material.transparent=true;obj.material.opacity=focused&&!related?.13:1;obj.material.depthWrite=!focused||related;obj.userData.outline.visible=related;obj.userData.outline.material.opacity=selected?.95:.6;
}}
function resize(){if(!viewReady)return;const w=$('viewport').clientWidth,h=$('viewport').clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);schedule();}
function updateCamera(){camera.position.set(target.x+spherical.radius*Math.sin(spherical.phi)*Math.sin(spherical.theta),target.y+spherical.radius*Math.cos(spherical.phi),target.z+spherical.radius*Math.sin(spherical.phi)*Math.cos(spherical.theta));camera.lookAt(target);camera.updateMatrixWorld();}
function schedule(){if(!viewReady||scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;render();});}
function overlaps(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
function render(){updateCamera();renderer.render(scene,camera);const w=$('viewport').clientWidth,h=$('viewport').clientHeight,mobile=w<550,occupied=[],focusOn=state.focus&&focusIds.size>0;let count=0,ordinaryCount=0;
 const vp=$('viewport').getBoundingClientRect();for(const id of ['axis-key','scene-status','analysis-panels']){const r=$(id).getBoundingClientRect();if(r.width&&r.height)occupied.push({x:r.left-vp.left-4,y:r.top-vp.top-3,w:r.width+8,h:r.height+6});}
 const leaders=$('label-leaders');leaders.replaceChildren();
 const priority=l=>primaryIds.has(l.e?.id)?3:focusOn&&focusIds.has(l.e?.id)?2:!l.e?1:0;
 const entries=[...labelEntries].sort((a,b)=>priority(b)-priority(a));
 const budget=mobile?(spherical.radius>38?6:12):(spherical.radius>44?16:spherical.radius<25?50:30);
 for(const l of entries){const pri=priority(l),required=pri>=2;let visible=!l.e||active(l.e);if(l.e&&state.labelMode==='selection'&&!required)visible=false;if(l.e&&!required&&ordinaryCount>=budget)visible=false;
 const v=l.pos.clone().project(camera),rawX=(v.x+1)*w/2,rawY=(1-v.y)*h/2,offscreen=v.z<-1||v.z>1||Math.abs(v.x)>1||Math.abs(v.y)>1;
 if(offscreen&&!required&&l.e)visible=false;
 l.el.classList.toggle('selected',primaryIds.has(l.e?.id));l.el.classList.toggle('related',required&&!primaryIds.has(l.e?.id));l.el.classList.toggle('dim',focusOn&&l.e&&!required);l.el.dataset.offscreen=String(offscreen);
 if(l.e){let text=state.labelMode==='full'||primaryIds.has(l.e.id)?l.e.label:l.e.shortLabel||l.e.label;if(mobile&&!primaryIds.has(l.e.id)&&text.length>12)text=text.slice(0,11)+'…';l.el.textContent=text+(required&&offscreen?' ↗':'');}
 if(!visible){l.el.style.display='none';continue;}
 l.el.style.display='block';const bw=Math.min(w-20,l.el.offsetWidth||50),bh=l.el.offsetHeight||23;
 const clamp=(val,min,max)=>Math.max(min,Math.min(max,val));let x=clamp(rawX,bw/2+6,w-bw/2-6),y=clamp(rawY,bh/2+8,h-bh/2-88);let best={x:x-bw/2,y:y-bh/2,w:bw+5,h:bh+4};
 if(occupied.some(b=>overlaps(best,b))){let found=null;const offsets=[0,26,-26,52,-52,78,-78,104,-104,130,-130,156,-156];for(const dy of offsets){for(const dx of [0,55,-55,110,-110,165,-165]){const xx=clamp(x+dx,bw/2+6,w-bw/2-6),yy=clamp(y+dy,bh/2+8,h-bh/2-88),test={x:xx-bw/2,y:yy-bh/2,w:bw+5,h:bh+4};if(!occupied.some(b=>overlaps(test,b))){found={xx,yy,test};break;}}if(found)break;}
 if(found){x=found.xx;y=found.yy;best=found.test;}else if(!required){l.el.style.display='none';continue;}else{ // Mandatory labels remain present; deterministic rail placement if crowded.
 let fit=null;for(let yy=20;yy<h-85;yy+=bh+5){for(let xx=bw/2+6;xx<w-bw/2;xx+=bw+8){const t={x:xx-bw/2,y:yy-bh/2,w:bw+5,h:bh+4};if(!occupied.some(b=>overlaps(t,b))){fit={xx,yy,t};break;}}if(fit)break;}if(fit){x=fit.xx;y=fit.yy;best=fit.t;}
 }}
 occupied.push(best);l.el.style.left=x+'px';l.el.style.top=y+'px';l.el.style.opacity='';if(l.e&&!required)ordinaryCount++;if(l.e)count++;
 if(required&&(Math.hypot(x-rawX,y-rawY)>18||offscreen)){const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',String(clamp(rawX,3,w-3)));line.setAttribute('y1',String(clamp(rawY,3,h-3)));line.setAttribute('x2',String(x));line.setAttribute('y2',String(y));line.setAttribute('stroke','#78949a');line.setAttribute('stroke-opacity','.32');line.setAttribute('stroke-width','1');leaders.append(line);}
 }
 $('scene-status').textContent=focusOn?`${focusIds.size} 関連対象／背景は淡色`:`${data.elements.filter(e=>e.position&&e.type!=='path'&&active(e)).length} 対象 · ${count} ラベル`;
}
function pan(dx,dy){const right=new THREE.Vector3().setFromMatrixColumn(camera.matrix,0),up=new THREE.Vector3().setFromMatrixColumn(camera.matrix,1),scale=spherical.radius*.0018;target.addScaledVector(right,-dx*scale);target.addScaledVector(up,dy*scale);}
function focus(id){select(id);fitFocus();}
function fitFocus(){if(!viewReady)return;const points=[...focusIds].map(id=>byId.get(id)).filter(e=>e?.position&&e.type!=='region'&&e.type!=='path');if(!points.length)return;const box=new THREE.Box3().setFromPoints(points.map(e=>vec(e.position)));box.getCenter(target);const size=box.getSize(new THREE.Vector3()),span=Math.max(size.x,size.y,size.z,6);spherical.radius=Math.min(80,Math.max(19,span*2.0/(Math.min(camera.aspect,1))));schedule();}
function preset(name){if(name==='reset'||name==='overview')boundary.enabled=false;const key=name==='reset'?'overview':name;state.preset=key;state.selected=null;state.compare=false;state.layers=Object.fromEntries(data.groups.map(g=>[g.id,g.default]));state.regions=Object.fromEntries(data.elements.filter(e=>e.type==='region'&&e.space!=='panel').map(e=>[e.id,e.visibleByDefault]));state.paths=Object.fromEntries(pathKinds.map(k=>[k,true]));state.focus=true;let id=null;let aim=[0,0,1],radius=40,theta=.83;
 if(key==='control'){id='C2';aim=[-2,0,1];radius=34;}
 if(key==='dna'){id='ex-dna';boundary.caseId=id;state.sigmaByExample[id]='translation';aim=[2,1,-3];radius=36;theta=.55;}
 if(key==='meaning'){id='M3';aim=[1,3,4];radius=34;}
 if(key==='ai'){state.compare=true;state.compareA='ex-llm';state.compareB='ex-embodied';aim=[0,1,3];radius=37;}
 if(viewReady){target.set(...aim);spherical={theta,phi:1.06,radius:radius*(innerWidth<760?1.15:1)};}
 if(name==='reset'){$('search').value='';state.labelMode='compact';$('label-mode').value='compact';state.sigmaByExample=Object.fromEntries(data.elements.filter(e=>e.type==='example').map(e=>[e.id,e.defaultSigma||'local']));}
 state.selected=id;sync();renderDetail();if(id||state.compare)openAudit();else{$('detail').classList.remove('open');updateMobileButtons();}}

function initScene(){if(!window.THREE)throw new Error('three.jsを読み込めません。vendorフォルダをindex.htmlと一緒に配置してください。');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(42,1,.1,250);target=new THREE.Vector3(0,0,1);raycaster=new THREE.Raycaster();raycaster.params.Line.threshold=.18;renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xf8faf9,0);$('viewport').prepend(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x9aaab0,2));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(10,20,15);scene.add(light);
 const grid=new THREE.GridHelper(24,12,0xcbd8dc,0xe2e9ea);grid.position.y=-7;grid.material.transparent=true;grid.material.opacity=.5;scene.add(grid);
 const origin=new THREE.Vector3(-11,-7,-9),axisDefs=[{dir:[1,0,0],length:23,label:'X｜持続・更新',col:0x527b93},{dir:[0,1,0],length:17,label:'Y｜変換・利用',col:0x77905d},{dir:[0,0,1],length:20,label:'Z｜組織化・意味拘束',col:0x9a7390}];
 for(const a of axisDefs){scene.add(new THREE.ArrowHelper(vec(a.dir),origin,a.length,a.col,.55,.3));const pos=origin.clone().add(vec(a.dir).multiplyScalar(a.length));const l=makeLabel(null,pos);l.textContent=a.label;}
 for(const e of data.elements){if(!e.position||e.type==='path')continue;let obj;const color=e.color||groups.get(e.group).color;
 if(e.type==='region'){obj=new THREE.Mesh(new THREE.SphereGeometry(1,24,16),new THREE.MeshBasicMaterial({color,transparent:true,opacity:e.id==='reg-bundle'?.055:.11,side:THREE.FrontSide,depthWrite:false}));obj.scale.set(...e.scale);const wire=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.IcosahedronGeometry(1,0)),new THREE.LineBasicMaterial({color,transparent:true,opacity:.10,depthWrite:false}));obj.add(wire);obj.renderOrder=-1;}
 else {let geometry=e.type==='example'?new THREE.OctahedronGeometry(.25):e.group==='process'?new THREE.BoxGeometry(.35,.35,.35):new THREE.SphereGeometry(.23,16,12);obj=new THREE.Mesh(geometry,new THREE.MeshLambertMaterial({color}));const outline=new THREE.LineSegments(new THREE.EdgesGeometry(geometry),new THREE.LineBasicMaterial({color:0x467e88,transparent:true,opacity:.6,depthWrite:false}));outline.scale.setScalar(1.18);outline.visible=false;obj.add(outline);obj.userData.outline=outline;pickables.push(obj);}
 obj.position.set(...e.position);obj.userData.id=e.id;scene.add(obj);objects.set(e.id,obj);makeLabel(e,obj.position.clone().add(new THREE.Vector3(0,e.type==='region'?e.scale[1]+.35:.48,0)));
 }
 for(const e of data.elements.filter(e=>e.type==='path')){const a=vec(byId.get(e.source).position),b=vec(byId.get(e.target).position);const curve=curveBetween(a,b,e.loop==='B'?-.55:.55);const color=e.loop==='B'?0x8e6aa5:e.loop==='A'?0x377a9b:palette[e.kind];const g=new THREE.Group();const line=lineCurve(curve,color,e.loop==='B');line.userData.id=e.id;g.add(line);pickables.push(line);const tip=curve.getPoint(.83),dir=curve.getTangent(.83).normalize();g.add(new THREE.ArrowHelper(dir,tip,.5,color,.32,.16));objects.set(e.id,g);scene.add(g);}
 associationGroup=new THREE.Group();scene.add(associationGroup);selectionHalo=new THREE.Mesh(new THREE.SphereGeometry(.38,18,12),new THREE.MeshBasicMaterial({color:0x367d87,wireframe:true,transparent:true,opacity:.5}));selectionHalo.visible=false;scene.add(selectionHalo);
 setupControls();new ResizeObserver(resize).observe($('viewport'));viewReady=true;resize();$('loading').hidden=true;
}
function setupControls(){const el=$('viewport'),pointers=new Map();let start=null,last=null,moved=false,pinch=null;el.addEventListener('contextmenu',e=>e.preventDefault());el.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;el.focus({preventScroll:true});el.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1){start={x:e.clientX,y:e.clientY};last={...start};moved=false;}if(pointers.size===2){const [a,b]=[...pointers.values()];pinch={d:Math.hypot(a.x-b.x,a.y-b.y),x:(a.x+b.x)/2,y:(a.y+b.y)/2};moved=true;}});
 el.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y),x=(a.x+b.x)/2,y=(a.y+b.y)/2;if(pinch){spherical.radius=THREE.MathUtils.clamp(spherical.radius*pinch.d/Math.max(d,1),7,95);pan(x-pinch.x,y-pinch.y);}pinch={d,x,y};moved=true;}else if(last){const dx=e.clientX-last.x,dy=e.clientY-last.y;if(Math.hypot(e.clientX-start.x,e.clientY-start.y)>5)moved=true;if(e.buttons===2||e.shiftKey)pan(dx,dy);else{spherical.theta-=dx*.006;spherical.phi=THREE.MathUtils.clamp(spherical.phi+dy*.006,.13,Math.PI-.13);}last={x:e.clientX,y:e.clientY};}schedule();});
 const finish=e=>{const click=pointers.size===1&&!moved&&e.type==='pointerup';pointers.delete(e.pointerId);pinch=null;last=null;if(click){const r=el.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=raycaster.intersectObjects(pickables,false).find(h=>{let o=h.object;while(o){if(!o.visible)return false;o=o.parent;}return true;});if(hit)select(hit.object.userData.id);}};el.addEventListener('pointerup',finish);el.addEventListener('pointercancel',finish);
 el.addEventListener('wheel',e=>{e.preventDefault();spherical.radius=THREE.MathUtils.clamp(spherical.radius*Math.exp(e.deltaY*.001),7,95);schedule();},{passive:false});el.addEventListener('keydown',e=>{const arrows={ArrowLeft:[-24,0],ArrowRight:[24,0],ArrowUp:[0,-24],ArrowDown:[0,24]};if(arrows[e.key]){e.preventDefault();const [dx,dy]=arrows[e.key];if(e.shiftKey)pan(dx,dy);else{spherical.theta-=dx*.006;spherical.phi=THREE.MathUtils.clamp(spherical.phi+dy*.006,.13,3.01);}schedule();}if(['+','=','-'].includes(e.key)){e.preventDefault();spherical.radius=THREE.MathUtils.clamp(spherical.radius*(e.key==='-'?1.1:.9),7,95);schedule();}});
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();$('loading').hidden=false;$('loading').textContent='描画が中断されました。ページを再読み込みしてください。左の一覧から定義は引き続き確認できます。';});
}
// Boundary overlays are editorial reading layers, never natural objects.
const boundary={enabled:false,layer:'both',presentation:'patchy',context:'systems_biology',conceptId:'concept_information_processing',scopeView:'current',difference:'all',caseId:'ex-bacteria'};
let boundaryGroup;
const statusColors={strong:0x247f83,candidate:0xbb8740,weak:0x8796a6,uncertain:0xa577a1};
function anchor(r){return data.relationAnchors[r]||r;}
function conceptNow(){return data.conceptualBoundaries.find(c=>c.id===boundary.conceptId);}
function usageNow(){return conceptNow()?.usageContexts[boundary.context];}
function boundaryCases(){return(state.compare?[state.compareA,state.compareB]:[boundary.caseId]).map(id=>byId.get(id)).filter(Boolean);}
function boundaryRecords(){return boundaryCases().flatMap(e=>{const claims=e.auditClaims||Object.entries(modeFor(e)?.evidence||{}).map(([relation,v])=>({...v,relation,anchor:anchor(relation),scope:state.sigmaByExample[e.id],sigma:modeFor(e)?.auditContext?.sigma,id:e.id+relation}));return claims.filter(c=>boundary.scopeView==='atlas'||c.scope===state.sigmaByExample[e.id]).map(c=>({...c,caseId:e.id,caseLabel:e.label}));});}
function included(r){return(usageNow()?.relations||[]).some(x=>x===r.relation||(x===r.anchor&&!x.startsWith('M2')&&!x.startsWith('M3')&&!x.startsWith('M4')));}
function differenceClass(r){return included(r)?(r.status==='strong'?'C':'B'):(r.status==='strong'?'A':'unmatched');}
function setBoundary(patch){Object.assign(boundary,patch);sync();renderDetail();}
function selectConcept(id){if(!data.conceptualBoundaries.some(c=>c.id===id))return;boundary.conceptId=id;boundary.enabled=true;sync();openAudit();}
function controlSelect(parent,label,id,options,value,fn){const l=dom('label','select-label',label),s=dom('select');s.id=id;for(const [v,t]of options){const o=dom('option','',t);o.value=v;s.append(o);}s.value=value;s.onchange=()=>fn(s.value);l.append(s);parent.append(l);return s;}
function renderBoundaryControls(){const p=$('boundary-controls');p.replaceChildren();p.append(dom('h2','','Boundary Layers'));check(p,'Patchy Boundary',null,boundary.enabled,v=>setBoundary({enabled:v}),'boundary-enabled');controlSelect(p,'表示する境界','boundary-layer',[['relation','Relation / 関係'],['concept','Concept / 概念使用'],['both','Both / 重ねる'],['difference','Difference / ズレ']],boundary.layer,v=>setBoundary({layer:v,enabled:true}));controlSelect(p,'読解モード','boundary-presentation',[['patchy','マダラ境界'],['co-stabilization','相互安定化']],boundary.presentation,v=>setBoundary({presentation:v,enabled:true}));controlSelect(p,'使用文脈','usage-context',Object.entries(data.usageContextLabels),boundary.context,v=>setBoundary({context:v,enabled:true}));controlSelect(p,'概念語（自然界のノードではない）','concept-term',data.conceptualBoundaries.map(c=>[c.id,c.label]),boundary.conceptId,selectConcept);controlSelect(p,'Σの断面','boundary-scope',[['current','選択したΣのみ'],['atlas','Σ横断 atlas：集約判定なし']],boundary.scopeView,v=>setBoundary({scopeView:v,enabled:true}));if(boundary.layer==='difference')controlSelect(p,'ズレの切り口','difference-filter',[['all','A・Bを強調／Cも表示'],['A','A：登録用法の外'],['B','B：圧縮・未確定'],['C','C：対応する部分']],boundary.difference,v=>setBoundary({difference:v}));p.append(btn('走化性のΣ横断デモ',()=>{boundary.scopeView='atlas';boundary.layer='both';boundary.context='systems_biology';boundary.conceptId='concept_information_processing';select('ex-bacteria');}));p.append(btn('DNA × 走化性',()=>{boundary.enabled=true;setCompare('ex-dna','ex-bacteria');}));p.append(dom('p','tag-help','色はclaimの根拠状態。輪郭・広さ・個数は成熟度でも測定値でもありません。'));}
function renderBoundary(){renderBoundaryControls();const p=$('boundary-detail');p.replaceChildren();if(boundaryGroup)disposeGroup(boundaryGroup);for(let i=labelEntries.length-1;i>=0;i--)if(labelEntries[i].boundary){labelEntries[i].el.remove();labelEntries.splice(i,1);}if(!boundary.enabled)return;
 const records=boundaryRecords(),concept=conceptNow(),usage=usageNow();p.append(dom('p','kind','BOUNDARY AUDIT / 関係と概念使用'),dom('h2','',concept.label));p.append(dom('p','scope-note',boundaryCases().map(e=>e.label).join(' × ')+'｜'+(boundary.scopeView==='atlas'?'Σ横断：各claimのΣを併記。最強値への集約なし。':'選択Σのみ。境界変更は別の対象命題への変更。')));p.append(dom('p','',`${data.usageContextLabels[boundary.context]}｜${usage?'編集上の用法対応候補':'この文脈の用法は未登録'}`));p.append(dom('p','tag-help','用法範囲は文献頻度・概念史を実証した境界ではありません。未登録は不成立を意味しません。'));
 if(boundary.presentation==='co-stabilization'){for(const interaction of data.boundaryInteractions){const box=dom('section','co-route');box.append(dom('h3','',interaction.direction==='world_to_concept'?'World → Concept':'Concept → World-reading'));const steps=interaction.steps||[];const ol=dom('ol');steps.forEach(t=>ol.append(dom('li','',typeof t==='string'?t:JSON.stringify(t))));box.append(ol,dom('p','tag-help','作業仮説。命名史の実証は未調査。世界の創造・真理の保証を意味しません。'));p.append(box);}section(p,'今回の検査例','翻訳対応の再現性が code の使用を制約する。一方 memory という問いはメチル化状態・時間窓・対照を選ぶ実験へつながる。これは概念形成史を確定した説明ではない。');}
 if(boundary.layer==='difference'){section(p,'Difference の読み方','A：strongだが登録用法に含まれない。B：同じ語への圧縮候補／含まれるがcandidate・weak・uncertain。C：strongで登録用法と対応する部分。Bの異質性は機構・Σ・根拠欄で比較する。これらは一致率でも語の正誤判定でもない。');}
 listSection(p,'この文脈で束ねる関係（編集案）',usage?.relations);listSection(p,'Common compressions',concept.commonCompressions);listSection(p,'禁止される飛躍',concept.forbiddenInferences);section(p,'用法の留保',usage?.notes);section(p,'Boundary status',concept.stabilization.status+' / 文脈依存。M4 ≠ Conceptual Boundary');section(p,'概念形成履歴','起源・安定化過程：unknown（未調査）。現在の登録文脈：'+Object.keys(concept.usageContexts).map(k=>data.usageContextLabels[k]).join('、'));
 const legend=dom('div','boundary-legend');for(const st of Object.keys(statusColors)){const sp=dom('span','evidence-badge '+st,data.evidenceLabels[st]);legend.append(sp);}p.append(legend,dom('p','tag-help','同じ関係でもΣ・対象過程・定義が違えば別claim。弱い≠不在、未確定≠否定。パッチは参照アンカー。M2各型などを同一の判定にまとめません。'));
 const claimsBox=dom('details','claim-list');claimsBox.open=true;claimsBox.append(dom('summary','','Σ付きの帰属を確認'));for(const r of records){const cl=differenceClass(r),row=dom('div','boundary-claim');row.dataset.status=r.status;row.append(btn(`${boundary.layer==='difference'?cl+'｜':''}${r.relation} · ${r.sigma||r.scope}`,()=>{state.selected=r.anchor;state.compare=false;sync();renderDetail();}));row.append(evidenceBadge(r),dom('small','',r.caseLabel));const more=dom('details');more.append(dom('summary','','根拠・留保'),dom('p','',r.basis||'未指定'),dom('p','',r.caveat||''),dom('p','tag-help','Evidence kind：'+(Array.isArray(r.evidenceKind)?r.evidenceKind.join(', '):r.evidenceKind||'未指定')));referenceList(more,r.references);row.append(more);claimsBox.append(row);}p.append(claimsBox);if(!records.length)p.append(dom('p','','このΣのclaimは未登録。強弱を補完しません。'));
 const targets=usage?.relations||[];const missing=targets.filter(t=>!records.some(r=>anchor(t)===r.anchor));section(p,'対応するclaimが未登録の用法要素',missing.join('、')||'なし');if(targets.includes('Shannon'))section(p,'Shannonは座標外','変数・分布・粒度・対照集合・必要ならチャネルを指定。概念の包摂領域を3Dに置きません。');
 if(!viewReady)return;if(!boundaryGroup){boundaryGroup=new THREE.Group();scene.add(boundaryGroup);}const displayRelation=boundary.layer!=='concept',displayConcept=boundary.layer!=='relation';
 if(displayRelation)records.forEach((r,i)=>{const e=byId.get(r.anchor);if(!e?.position||e.space==='panel')return;const cl=differenceClass(r);let opacity=.15;if(boundary.layer==='difference'){opacity=(boundary.difference==='all'?(cl==='A'||cl==='B'):(cl===boundary.difference))?.20:.025;}const mesh=new THREE.Mesh(new THREE.SphereGeometry(.70,16,12),new THREE.MeshBasicMaterial({color:statusColors[r.status]||0xaaaaaa,transparent:true,opacity,depthWrite:false}));mesh.position.set(...e.position);mesh.position.x+=((i%3)-1)*.13;mesh.position.z+=((i%2)-.5)*.13;boundaryGroup.add(mesh);const line=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.IcosahedronGeometry(.70,1)),new THREE.LineBasicMaterial({color:statusColors[r.status],transparent:true,opacity:opacity*1.8,depthWrite:false}));line.position.copy(mesh.position);boundaryGroup.add(line);});
 if(displayConcept){const positions=[];[...new Set(targets.map(anchor))].forEach(id=>{const e=byId.get(id);if(!e?.position||e.space==='panel')return;positions.push(e.position);const halo=new THREE.Mesh(new THREE.TorusGeometry(.98,.025,6,40),new THREE.MeshBasicMaterial({color:0xb36548,transparent:true,opacity:.65,depthWrite:false}));halo.position.set(...e.position);halo.quaternion.copy(camera.quaternion);boundaryGroup.add(halo);});if(positions.length){const pos=vec(positions[0]).add(new THREE.Vector3(0,1.5,0)),label=makeLabel(null,pos);label.classList.add('concept-label');label.textContent='◯ '+concept.label+' · 用法領域';label.setAttribute('role','button');label.tabIndex=0;label.onclick=()=>{openAudit();$('boundary-detail').scrollIntoView({block:'start'});};label.onkeydown=e=>{if(e.key==='Enter')label.click();};labelEntries[labelEntries.length-1].boundary=true;}}
}

for(const g of data.groups)check($('layer-list'),g.label,g.color,state.layers[g.id],v=>{state.layers[g.id]=v;state.preset='custom';sync();},'layer-'+g.id);
for(const e of data.elements.filter(e=>e.type==='region'&&e.space!=='panel'))check($('region-list'),e.label,null,state.regions[e.id],v=>{state.regions[e.id]=v;if(v)state.layers[e.group]=true;sync();},'region-'+e.id);
for(const k of Object.keys(state.paths))check($('path-list'),k,null,true,v=>{state.paths[k]=v;sync();},'path-'+k);
$('toggle-layers').onclick=()=>showMobile('layers');$('toggle-detail').onclick=()=>showMobile('detail');
$('label-mode').onchange=e=>{state.labelMode=e.target.value;schedule();};$('search').oninput=renderList;
$('defaults').onclick=()=>preset('reset');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>preset(b.dataset.view));

$('focus-mode').onchange=e=>{state.focus=e.target.checked;sync();};
$('clear-focus').onclick=clearFocus;$('fit-focus').onclick=fitFocus;
$('compare-toggle').onclick=()=>state.compare?clearFocus():setCompare();
$('sheet-handle').onclick=()=>$('detail').classList.toggle('expanded');
try{initScene();}catch(e){$('loading').hidden=false;$('loading').textContent='3Dを開始できません：'+e.message+' 左の一覧と説明は利用できます。';console.error(e);}
preset('overview');document.fonts?.ready.then(schedule);
window.FigureExplorer={setBoundary,selectConcept,getBoundary:()=>({...boundary,records:boundaryRecords()}),select,preset,setSigma,setCompare,clearFocus,fitFocus,getState:()=>JSON.parse(JSON.stringify(state)),getFocus:()=>[...focusIds],getCamera:()=>({spherical:{...spherical},target:target?.toArray()}),ready:()=>viewReady,data,inspect:()=>[...objects].map(([id,o])=>({id,visible:o.visible,opacity:o.material?.opacity,label:labelEntries.find(l=>l.e?.id===id)?.el.style.display}))};
})();
